export { default as LandingPage } from './LandingPage'
export { StudentLogin } from './StudentLogin'
export { StudentDashboard } from './StudentDashboard'
export { ExamPage } from './ExamPage'
export { ExamInterfacePage } from './ExamInterfacePage'
export { ResultPage } from './ResultPage'
export { AdminLogin } from './AdminLogin'
export { AdminDashboard } from './AdminDashboard'
export { AdminMonitoring } from './AdminMonitoring'
export { AdminSchedule } from './AdminSchedule'
export { AdminStudents } from './AdminStudents'
export { AdminExams } from './AdminExams'
export { AdminQuestions } from './AdminQuestions'
export { AdminResults } from './AdminResults'
export { AdminSettings } from './AdminSettings'
export { AnnouncementsPage } from './AnnouncementsPage'
export { ResultsPage } from './ResultsPage'
export { ProfilePage } from './ProfilePage'
